### ISSUE TITLE
Création page

### ISSUE THREAD

**Issue by d-stephane** [fkeloks/BDS_Framework#7]
je viens de tester la création d'une simple page appelée **mysql**  
J'ai l'erreur suivante **Class 'App\Controllers\mysqlController' not found** quand je l'appelle.  
Fichiers créés :
- app/controllers/mysqlController.php
```php
<?php
namespace App\Controllers;

class mysqlController extends \BDSCore\BaseController
{
   public function index() {
        $this->render('mysql.twig');
    }
}
```
- app/views/mysql.twig
```html
{% extends 'globals/default.twig' %}
{% block title %}Mysql{% endblock %}
{% block body %}
    <div class="block-center">
        <h1>Test connexion à Mysql</h1>
    </div>
{% endblock %}
```
- fichier config/router.php modifié
```php
'mysqlPage' => ['get', '/mysql', 'mysqlController@index'],
```
Y a autre chose à faire pour rajouter une page ?
Un cache à vider, un truc à régénérer ?

**Comment by fkeloks** [comment]
Bonjour,

Je vient de tester ce code chez moi avec les mêmes nom de fichier : aucune erreur.
Le problème pourrait venir de l'autoloader de composer.

Dans le doute, la solution serait d'essayer la commande : 
```
composer dump-autoload
```

Concernant le cache, le router n'en génère pas donc le problème ne semble pas pouvoir venir de là.

**Comment by fkeloks** [comment]
Problème reconnu :

Sur d'autres systèmes que le mien, un composer dump-autoload semble obligatoire après chaque création de nouveau fichier.

Je recherche une solution pour corriger celà.
Cordialement

**Comment by fkeloks** [comment]
Bug corrigé.

Cordialement.
